### PR TITLE
address issues from lighthouse audit

### PR DESCRIPTION
**Pull request by lpmi-13**
- address accessibility issues: add html lang attribute, add ability for user to zoom, add discernable names to links
- address security issue: update to jquery 3.5.1 to fix 3.4.1 vulnerability
- address seo issues: add meta description

current site score:

lighthouse for current page

score with this commit:

lighthouse score with current commit

### CODE REVIEW

**Comment by lpmi-13** [comment]
I chose to leave the colour contrasts as they are, just since it felt like too much editorialising.

I'm also happy to split this out into separate PRs for a11y/security/seo, if that would be preferable.

**Comment by leaanthony** [comment]
Thanks very much for this! Would it be possible to do a PR sans the jquery update? I will ensure it gets updated, it's just hard to review as part of a PR. Thank you!

**Comment by lpmi-13** [comment]
alright, should be good to go!

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks!

**Pull request merged**
