### PR TITLE
New language (Simplified Chinese) support

### PR DESCRIPTION
**Pull request by misitebao**
@leaanthony @tmclane 
1. Add multi language (Simplified Chinese) support and translate part of the document content.
2. Due to the official website（ wails.app ）Access speed is not ideal, so I set up a mirror website in China（ wails.top ）And added GitHub actions script to deploy automatically. However, I have verified the warehouse address, which will not affect your warehouse.

If you have any questions, please contact me and I will deal with it as soon as possible.Thank you!

### CODE REVIEW

**Comment by leaanthony** [comment]
Hi. Looks like the PR might be incomplete: https://app.netlify.com/sites/sad-colden-a495a3/deploys/5f9695b9df4dc500077eb89a

**Comment by misitebao** [comment]
@leaanthony 
This problem may be caused by your hugo version. When I used github actions to build for the first time, I used an older version, which caused the build to fail, but when I switched to the latest version, there was no problem. You You can try to set the build version to the latest（v0.76.5）.

If the problem persists, then I am sorry, maybe I need to learn Netlify, and then try to find the problem.

**Review by leaanthony — APPROVED** [review]

**Comment by misitebao** [comment]
@leaanthony 
Huh? Has the problem been solved? Can you tell me whether it is caused by the hugo version or other problems?Thank you！

**Comment by leaanthony** [comment]
Yes, Hugo version. Netlify allows you to specify this so I did😃

**Comment by misitebao** [comment]
@leaanthony 
However, I added a netlify.toml file in the root directory of the project, but the PR page still prompted a problem at that time. :rofl:

**Comment by leaanthony** [comment]
Yeah, I had to explicitlyset a variable

**Pull request merged**
