### PR TITLE
Cerberus Service Manager showcase submission

### PR DESCRIPTION
**Pull request by snmed**

### CODE REVIEW

**Comment by leaanthony** [comment]
Hi. Thanks for this. It looks like there might be an issue with URLs as the preview site doesn't appearto work correctly: https://deploy-preview-30--wails.netlify.app/showcase/

**Comment by snmed** [comment]
Hi, hmm strange I run it on my local machine and it worked as excpected.
I'll check it again tomorrow and update the pull request as soon I found
the problem.

Lea Anthony ***@***.***> schrieb am Fr., 16. Apr. 2021, 22:45:

**Comment by leaanthony** [comment]
Potentially the preview is messed up. Looks ok to me.

**Comment by leaanthony** [comment]
Yup! Working fine. Thanks for your contribution and congrats on a great looking app!

**Comment by snmed** [comment]
Thanks, nice that the problem has been solved overnight by it self.

Lea Anthony ***@***.***> schrieb am Sa., 17. Apr. 2021, 00:46:

**Pull request merged**
